= `GmailSafe v0.0.1`

The goal of this project is to implement a https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/[`Spring Boot`] Web Java application that communicates with a GMail inbox account using https://developers.google.com/gmail/api/[`GMail API`].

== Endpoints

- `GET /api/v1/backups`
- `POST /api/v1/backups`
- `GET /api/v1/backups/exports/{backupId}`
- `GET /api/v1/backups/exports/{backupId}/{label}`

== Running the application without credentials

. You need to enable the GMail API. In order to do it, access this website https://developers.google.com/gmail/api/quickstart/java and follow the instructions in `Step 1: Turn on the GMail API`. Download the `credentials.json` file. It contains the credentials that will be used on the next steps.
. Copy the credentials.json file and paste it into src/main/resources folder
. Open a terminal and inside `springboot-gmail` folder, run the following command
+
[source]
----
./mvnw spring-boot:run
----

Access the following url to provide permission

[source]
----
  https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=822661997257-jthda24kn4reomdq2delbufvd6qa7iec.apps.googleusercontent.com&redirect_uri=http://localhost:8888/Callback&response_type=code&scope=https://www.googleapis.com/auth/gmail.readonly
----  

== Running the jar (GMail credentials already set will return mail from my account)
[source]
----
java -jar <location of the jar>/springboot-gmail-0.0.1-SNAPSHOT.jar
----

== Testing with Swagger(not recommended for zip download endpoints)
[source]
----
Open the following location http://localhost:8080/swagger-ui.html
----

== Copy paste endpoints in browser (recommended for zip download endpoints)

[source]
----
http://localhost:8080/api/v1/backups/exports/{backupId}
http://localhost:8080/api/v1/backups/exports/{backupId}/{label}
----

